"""struttura iniziale con reparti e voci checklist

Crea le otto tabelle del Cruscotto e ci mette dentro i dati fissi: i tre
reparti e le 20 voci della checklist di dimissione. Sono dati che devono
esistere prima che chiunque apra il programma, quindi il posto giusto è qui
e non un comando da lanciare a parte, che qualcuno prima o poi dimenticherà.

Revision ID: 042c1d4c264a
Revises:
Create Date: 2026-09-18 10:03:52.470223

"""
import sys
from pathlib import Path

from alembic import op
import sqlalchemy as sa

# La migrazione viene eseguita da Alembic, che non conosce la cartella del
# progetto: gliela indichiamo, così può leggere l'elenco dei dati fissi
# invece di tenerne una seconda copia qui dentro.
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from app.dati_fissi import REPARTI, VOCI_CHECKLIST  # noqa: E402


# revision identifiers, used by Alembic.
revision = '042c1d4c264a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.Unicode(length=10), nullable=False),
    sa.Column('nome', sa.Unicode(length=60), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice')
    )
    op.create_table('utente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=50), nullable=False),
    sa.Column('nome', sa.Unicode(length=80), nullable=False),
    sa.Column('cognome', sa.Unicode(length=80), nullable=False),
    sa.Column('ruolo', sa.Unicode(length=12), nullable=False),
    sa.Column('password_hash', sa.Unicode(length=255), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('deve_cambiare_password', sa.Boolean(), nullable=False),
    sa.Column('tentativi_falliti', sa.Integer(), nullable=False),
    sa.Column('bloccato_fino', sa.DateTime(), nullable=True),
    sa.Column('ultimo_accesso', sa.DateTime(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=False),
    sa.Column('creato_da', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creato_da'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('voce_checklist',
    sa.Column('codice', sa.Unicode(length=20), nullable=False),
    sa.Column('testo', sa.Unicode(length=120), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('attiva', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codice')
    )
    op.create_table('evento_audit',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quando', sa.DateTime(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('username_tentato', sa.Unicode(length=50), nullable=True),
    sa.Column('azione', sa.Unicode(length=30), nullable=False),
    sa.Column('entita', sa.Unicode(length=20), nullable=True),
    sa.Column('entita_id', sa.Integer(), nullable=True),
    sa.Column('dettagli', sa.Unicode(length=255), nullable=True),
    sa.Column('indirizzo_ip', sa.Unicode(length=45), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_audit_azione'), ['azione'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_audit_quando'), ['quando'], unique=False)

    op.create_table('paziente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Unicode(length=80), nullable=False),
    sa.Column('cognome', sa.Unicode(length=80), nullable=False),
    sa.Column('posto_letto', sa.Unicode(length=10), nullable=False),
    sa.Column('gravita', sa.Unicode(length=6), nullable=False),
    sa.Column('data_arrivo', sa.Date(), nullable=False),
    sa.Column('data_dimissione_presunta', sa.Date(), nullable=True),
    sa.Column('stato', sa.Unicode(length=12), nullable=False),
    sa.Column('creato_il', sa.DateTime(), nullable=False),
    sa.Column('creato_da', sa.Integer(), nullable=False),
    sa.Column('eliminato_il', sa.DateTime(), nullable=True),
    sa.Column('eliminato_da', sa.Integer(), nullable=True),
    sa.CheckConstraint('data_dimissione_presunta IS NULL OR data_dimissione_presunta >= data_arrivo', name='ck_paziente_dimissione_dopo_arrivo'),
    sa.ForeignKeyConstraint(['creato_da'], ['utente.id'], ),
    sa.ForeignKeyConstraint(['eliminato_da'], ['utente.id'], ),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paziente', schema=None) as batch_op:
        batch_op.create_index('ix_paziente_cruscotto', ['stato', 'reparto_id', 'data_dimissione_presunta'], unique=False)
        batch_op.create_index('ux_paziente_letto_occupato', ['reparto_id', 'posto_letto'], unique=True, sqlite_where=sa.text("stato = 'RICOVERATO'"), mssql_where=sa.text("stato = 'RICOVERATO'"))

    op.create_table('checklist_spunta',
    sa.Column('paziente_id', sa.Integer(), nullable=False),
    sa.Column('voce_codice', sa.Unicode(length=20), nullable=False),
    sa.ForeignKeyConstraint(['paziente_id'], ['paziente.id'], ),
    sa.ForeignKeyConstraint(['voce_codice'], ['voce_checklist.codice'], ),
    sa.PrimaryKeyConstraint('paziente_id', 'voce_codice')
    )
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paziente_id', sa.Integer(), nullable=False),
    sa.Column('autore_id', sa.Integer(), nullable=False),
    sa.Column('autore_nome', sa.Unicode(length=170), nullable=False),
    sa.Column('autore_ruolo', sa.Unicode(length=12), nullable=False),
    sa.Column('testo', sa.UnicodeText(), nullable=False),
    sa.Column('data_nota', sa.Date(), nullable=False),
    sa.Column('creata_il', sa.DateTime(), nullable=False),
    sa.Column('modificata_il', sa.DateTime(), nullable=True),
    sa.Column('eliminata', sa.Boolean(), nullable=False),
    sa.Column('eliminata_il', sa.DateTime(), nullable=True),
    sa.Column('eliminata_da', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autore_id'], ['utente.id'], ),
    sa.ForeignKeyConstraint(['eliminata_da'], ['utente.id'], ),
    sa.ForeignKeyConstraint(['paziente_id'], ['paziente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.create_index('ix_nota_agenda', ['paziente_id', 'eliminata', 'data_nota', 'id'], unique=False)

    op.create_table('nota_versione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('testo_precedente', sa.UnicodeText(), nullable=False),
    sa.Column('sostituito_il', sa.DateTime(), nullable=False),
    sa.Column('sostituito_da', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['nota.id'], ),
    sa.ForeignKeyConstraint(['sostituito_da'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    _inserisci_dati_fissi()


def _inserisci_dati_fissi():
    """Riempie reparto e voce_checklist.

    Usiamo op.bulk_insert con una descrizione "leggera" delle tabelle invece
    dei modelli di models.py. Sembra un doppione, ma è voluto: una migrazione
    deve continuare a funzionare identica anche fra due anni, quando models.py
    sarà cambiato. Descrivendo qui le colonne che servono, questa migrazione
    resta congelata a com'era il giorno in cui è stata scritta.
    """
    tabella_reparto = sa.table(
        "reparto",
        sa.column("codice", sa.Unicode),
        sa.column("nome", sa.Unicode),
        sa.column("ordine", sa.Integer),
    )
    op.bulk_insert(
        tabella_reparto,
        [
            {"codice": codice, "nome": nome, "ordine": ordine}
            for codice, nome, ordine in REPARTI
        ],
    )

    tabella_voce = sa.table(
        "voce_checklist",
        sa.column("codice", sa.Unicode),
        sa.column("testo", sa.Unicode),
        sa.column("ordine", sa.Integer),
        sa.column("attiva", sa.Boolean),
    )
    op.bulk_insert(
        tabella_voce,
        [
            {"codice": codice, "testo": testo, "ordine": posizione, "attiva": True}
            # enumerate parte da 1: l'ordine è quello della lista in dati_fissi.
            for posizione, (codice, testo) in enumerate(VOCI_CHECKLIST, start=1)
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_versione')
    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.drop_index('ix_nota_agenda')

    op.drop_table('nota')
    op.drop_table('checklist_spunta')
    with op.batch_alter_table('paziente', schema=None) as batch_op:
        batch_op.drop_index('ux_paziente_letto_occupato', sqlite_where=sa.text("stato = 'RICOVERATO'"), mssql_where=sa.text("stato = 'RICOVERATO'"))
        batch_op.drop_index('ix_paziente_cruscotto')

    op.drop_table('paziente')
    with op.batch_alter_table('evento_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_audit_quando'))
        batch_op.drop_index(batch_op.f('ix_evento_audit_azione'))

    op.drop_table('evento_audit')
    op.drop_table('voce_checklist')
    op.drop_table('utente')
    op.drop_table('reparto')
    # ### end Alembic commands ###
